server:
    port: 8082

security:
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: http://localhost:8080/oauth/token
    resource:
      userInfoUri: http://localhost:8080/user/me